"""Versioned M9 training-intervention registry and bounded selection API."""

from .model import (
    ExerciseDefinition,
    ExercisePositionSource,
    HypothesisInterventionMapping,
    HypothesisInterventionMappingRef,
    InterventionApplicability,
    InterventionMappingActorKind,
    InterventionMappingProvenance,
    InterventionRegistry,
    InterventionSelectionDecision,
    InterventionSelectionDecisionKind,
    InterventionSelectionPolicy,
    InterventionSelectionPolicyRef,
    TrainingContentActorKind,
    TrainingContentProvenance,
    TrainingInterventionDefinition,
    TrainingInterventionRef,
)
from .registry import (
    TrainingInterventionError,
    build_intervention_registry,
    define_exercise,
    define_intervention_selection_policy,
    define_training_intervention,
    record_hypothesis_intervention_mapping,
    select_training_intervention,
)

__all__ = [
    "ExerciseDefinition",
    "ExercisePositionSource",
    "HypothesisInterventionMapping",
    "HypothesisInterventionMappingRef",
    "InterventionApplicability",
    "InterventionMappingActorKind",
    "InterventionMappingProvenance",
    "InterventionRegistry",
    "InterventionSelectionDecision",
    "InterventionSelectionDecisionKind",
    "InterventionSelectionPolicy",
    "InterventionSelectionPolicyRef",
    "TrainingContentActorKind",
    "TrainingContentProvenance",
    "TrainingInterventionDefinition",
    "TrainingInterventionError",
    "TrainingInterventionRef",
    "build_intervention_registry",
    "define_exercise",
    "define_intervention_selection_policy",
    "define_training_intervention",
    "record_hypothesis_intervention_mapping",
    "select_training_intervention",
]
