"""M46 adaptive Socratic tutoring proposals over the qualified M8 lifecycle.

M46 chooses a bounded next pedagogical action from exact learner/tutor context. It
never executes that action. M8 remains the exposure/capture/reveal authority; model
language remains downstream and is not generated by this module.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, TypeAlias

from chess_mentor_engine.chess import canonical_json
from chess_mentor_engine.learner_intelligence.evidence_synthesis import (
    EvidenceSynthesisReference,
)
from chess_mentor_engine.learner_intelligence.mentor_queue import (
    MentorQueue,
    MentorQueueItem,
)
from chess_mentor_engine.learner_intelligence.progress_model import (
    LearnerProgressHypothesis,
    LearnerProgressView,
)
from chess_mentor_engine.learner_intelligence.transfer_retest import TransferRetestPlan
from chess_mentor_engine.learning import HypothesisRevisionRef

from .model import TutorSession

ADAPTIVE_TUTOR_POLICY_SCHEMA_VERSION = "m46.adaptive-tutor-policy.v1"
ADAPTIVE_TUTOR_PROPOSAL_SCHEMA_VERSION = "m46.adaptive-tutor-proposal.v1"

AdaptiveTutorAction: TypeAlias = Literal[
    "CONTINUE_BASELINE_CAPTURE",
    "ASK_CANDIDATE_MOVES",
    "ASK_THREATS",
    "ASK_DEFENDER_ROLE",
    "ASK_EVALUATION_FACTORS",
    "ASK_PLAN",
    "GIVE_MINIMAL_HINT",
    "GIVE_CONCEPT_HINT",
    "GIVE_DIRECTIONAL_HINT",
    "REVEAL_TACTICAL_RELATION",
    "REVEAL_ENGINE_LINE",
    "ASK_REFLECTION",
    "NO_FURTHER_ACTION",
]
ExposureEffect: TypeAlias = Literal[
    "none",
    "assisted_followup",
    "objective_reveal",
    "post_reveal",
]
ResponseEvidenceClass: TypeAlias = Literal[
    "baseline_unassisted",
    "assisted_followup",
    "post_reveal_reflection",
    "none",
]

_PRE_BASELINE_STATES = {"selected", "presented", "capturing"}
_POST_REVEAL_STATES = {"revealed", "compared", "explained"}
_TRANSFER_ACTIONS = {"RUN_NEAR_TRANSFER_TEST", "RUN_FAR_TRANSFER_TEST"}
_EVIDENCE_ACTIONS = {
    "COLLECT_NEW_EVIDENCE",
    "CHALLENGE_HYPOTHESIS",
    "PRESENT_CONTROL",
}


def _digest(value: object) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def _nonempty(name: str, value: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must not be empty")


def _timestamp(name: str, value: str) -> None:
    _nonempty(name, value)
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError(f"{name} must be an ISO-8601 timestamp") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ValueError(f"{name} must include a timezone offset")


def _ref(kind: str, ref_id: str, fingerprint: str) -> EvidenceSynthesisReference:
    return EvidenceSynthesisReference(kind, ref_id, fingerprint)


def _session_ref(session: TutorSession) -> EvidenceSynthesisReference:
    return _ref(
        "tutor_session_snapshot",
        session.tutor_session_id,
        session.snapshot_fingerprint,
    )


def _view_ref(view: LearnerProgressView) -> EvidenceSynthesisReference:
    return _ref("learner_progress_view", view.view_id, view.fingerprint)


def _queue_ref(queue: MentorQueue) -> EvidenceSynthesisReference:
    return _ref("mentor_queue", queue.queue_id, queue.fingerprint)


def _queue_item_ref(item: MentorQueueItem) -> EvidenceSynthesisReference:
    return _ref(
        "mentor_queue_item",
        item.diagnostic_candidate_ref.ref_id,
        _digest(item.to_dict()),
    )


def _transfer_ref(plan: TransferRetestPlan) -> EvidenceSynthesisReference:
    return _ref("transfer_retest_plan", plan.transfer_plan_id, plan.fingerprint)


@dataclass(frozen=True, slots=True)
class AdaptiveTutorPolicyRef:
    policy_id: str
    version: str
    fingerprint: str

    def __post_init__(self) -> None:
        _nonempty("policy_id", self.policy_id)
        _nonempty("version", self.version)
        _nonempty("fingerprint", self.fingerprint)

    def to_dict(self) -> dict[str, str]:
        return {
            "policy_id": self.policy_id,
            "version": self.version,
            "fingerprint": self.fingerprint,
        }


@dataclass(frozen=True, slots=True)
class AdaptiveTutorPolicy:
    policy_id: str
    version: str
    fingerprint: str
    preserve_m8_baseline_until_frozen: bool
    use_recognition_question_for_teaching: bool
    evidence_actions_reveal_after_freeze: bool
    post_reveal_reflection: bool
    claim_scope: str = "transparent_pedagogical_action_policy"
    schema_version: str = ADAPTIVE_TUTOR_POLICY_SCHEMA_VERSION

    def __post_init__(self) -> None:
        for name, value in (
            ("policy_id", self.policy_id),
            ("version", self.version),
            ("fingerprint", self.fingerprint),
        ):
            _nonempty(name, value)
        if self.schema_version != ADAPTIVE_TUTOR_POLICY_SCHEMA_VERSION:
            raise ValueError("unsupported M46 adaptive-tutor policy schema")
        if self.claim_scope != "transparent_pedagogical_action_policy":
            raise ValueError("M46 policy claim scope is invalid")
        if not self.preserve_m8_baseline_until_frozen:
            raise ValueError("M46 v1 must preserve the M8 pre-reveal baseline")

    def identity_payload(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "policy_id": self.policy_id,
            "version": self.version,
            "preserve_m8_baseline_until_frozen": (
                self.preserve_m8_baseline_until_frozen
            ),
            "use_recognition_question_for_teaching": (
                self.use_recognition_question_for_teaching
            ),
            "evidence_actions_reveal_after_freeze": (
                self.evidence_actions_reveal_after_freeze
            ),
            "post_reveal_reflection": self.post_reveal_reflection,
            "claim_scope": self.claim_scope,
        }

    @property
    def ref(self) -> AdaptiveTutorPolicyRef:
        return AdaptiveTutorPolicyRef(
            self.policy_id,
            self.version,
            self.fingerprint,
        )


@dataclass(frozen=True, slots=True)
class AdaptiveTutorProposal:
    proposal_id: str
    fingerprint: str
    participant_id: str
    tutor_session_ref: EvidenceSynthesisReference
    learner_progress_view_ref: EvidenceSynthesisReference
    mentor_queue_ref: EvidenceSynthesisReference | None
    mentor_queue_item_ref: EvidenceSynthesisReference | None
    transfer_plan_ref: EvidenceSynthesisReference | None
    hypothesis_id: str
    hypothesis_revision_ref: HypothesisRevisionRef
    tutor_session_state: str
    learner_next_action: str
    action: AdaptiveTutorAction
    rendered_prompt: str | None
    concept_ids: tuple[str, ...]
    exposure_effect: ExposureEffect
    response_evidence_class: ResponseEvidenceClass
    reasons: tuple[str, ...]
    blocking_uncertainty: tuple[str, ...]
    policy_ref: AdaptiveTutorPolicyRef
    created_at: str
    execution_authority: Literal["proposal_only"] = "proposal_only"
    model_language: Literal["not_generated"] = "not_generated"
    mastery: Literal["not_established"] = "not_established"
    schema_version: str = ADAPTIVE_TUTOR_PROPOSAL_SCHEMA_VERSION

    def __post_init__(self) -> None:
        for name, value in (
            ("proposal_id", self.proposal_id),
            ("fingerprint", self.fingerprint),
            ("participant_id", self.participant_id),
            ("hypothesis_id", self.hypothesis_id),
            ("tutor_session_state", self.tutor_session_state),
            ("learner_next_action", self.learner_next_action),
        ):
            _nonempty(name, value)
        _timestamp("created_at", self.created_at)
        if self.schema_version != ADAPTIVE_TUTOR_PROPOSAL_SCHEMA_VERSION:
            raise ValueError("unsupported M46 adaptive-tutor proposal schema")
        if len(set(self.concept_ids)) != len(self.concept_ids):
            raise ValueError("M46 concept IDs must be unique")
        if not self.reasons:
            raise ValueError("M46 proposal requires explicit reasons")
        if len(set(self.reasons)) != len(self.reasons):
            raise ValueError("M46 proposal reasons must be unique")
        if len(set(self.blocking_uncertainty)) != len(self.blocking_uncertainty):
            raise ValueError("M46 blocking uncertainty must be unique")
        if (self.mentor_queue_ref is None) != (self.mentor_queue_item_ref is None):
            raise ValueError("M46 mentor queue and item refs must appear together")
        if self.execution_authority != "proposal_only":
            raise ValueError("M46 cannot grant tutoring execution authority")
        if self.model_language != "not_generated":
            raise ValueError("M46 deterministic proposal cannot claim model language")
        if self.mastery != "not_established":
            raise ValueError("M46 cannot establish mastery")

    def identity_payload(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "participant_id": self.participant_id,
            "tutor_session_ref": self.tutor_session_ref.to_dict(),
            "learner_progress_view_ref": self.learner_progress_view_ref.to_dict(),
            "mentor_queue_ref": (
                None if self.mentor_queue_ref is None else self.mentor_queue_ref.to_dict()
            ),
            "mentor_queue_item_ref": (
                None
                if self.mentor_queue_item_ref is None
                else self.mentor_queue_item_ref.to_dict()
            ),
            "transfer_plan_ref": (
                None
                if self.transfer_plan_ref is None
                else self.transfer_plan_ref.to_dict()
            ),
            "hypothesis_id": self.hypothesis_id,
            "hypothesis_revision_ref": self.hypothesis_revision_ref.to_dict(),
            "tutor_session_state": self.tutor_session_state,
            "learner_next_action": self.learner_next_action,
            "action": self.action,
            "rendered_prompt": self.rendered_prompt,
            "concept_ids": list(self.concept_ids),
            "exposure_effect": self.exposure_effect,
            "response_evidence_class": self.response_evidence_class,
            "reasons": list(self.reasons),
            "blocking_uncertainty": list(self.blocking_uncertainty),
            "policy_ref": self.policy_ref.to_dict(),
            "created_at": self.created_at,
            "execution_authority": self.execution_authority,
            "model_language": self.model_language,
            "mastery": self.mastery,
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "fingerprint": self.fingerprint,
            **self.identity_payload(),
        }


def build_default_adaptive_tutor_policy() -> AdaptiveTutorPolicy:
    payload = {
        "schema_version": ADAPTIVE_TUTOR_POLICY_SCHEMA_VERSION,
        "policy_id": "m46.default-adaptive-tutor-policy",
        "version": "1",
        "preserve_m8_baseline_until_frozen": True,
        "use_recognition_question_for_teaching": True,
        "evidence_actions_reveal_after_freeze": True,
        "post_reveal_reflection": True,
        "claim_scope": "transparent_pedagogical_action_policy",
    }
    return AdaptiveTutorPolicy(
        policy_id=payload["policy_id"],
        version=payload["version"],
        fingerprint=_digest(payload),
        preserve_m8_baseline_until_frozen=True,
        use_recognition_question_for_teaching=True,
        evidence_actions_reveal_after_freeze=True,
        post_reveal_reflection=True,
    )


def validate_adaptive_tutor_policy(policy: AdaptiveTutorPolicy) -> None:
    if _digest(policy.identity_payload()) != policy.fingerprint:
        raise ValueError("M46 adaptive-tutor policy fingerprint mismatch")


def _validate_session(session: TutorSession) -> None:
    expected = _digest(session.to_dict(include_snapshot_fingerprint=False))
    if expected != session.snapshot_fingerprint:
        raise ValueError("M46 tutor-session snapshot fingerprint mismatch")


def _validate_view(view: LearnerProgressView) -> None:
    expected = _digest(view.identity_payload())
    if expected != view.fingerprint:
        raise ValueError("M46 learner-progress view fingerprint mismatch")
    if view.view_id != f"learner_progress_view_{expected[:20]}":
        raise ValueError("M46 learner-progress view identity mismatch")


def _validate_queue_context(
    *,
    queue: MentorQueue | None,
    item: MentorQueueItem | None,
    view: LearnerProgressView,
    session: TutorSession,
    hypothesis_id: str,
) -> tuple[EvidenceSynthesisReference | None, EvidenceSynthesisReference | None]:
    if (queue is None) != (item is None):
        raise ValueError("M46 mentor queue and item must be supplied together")
    if queue is None or item is None:
        return None, None
    expected = _digest(queue.identity_payload())
    if queue.fingerprint != expected or queue.queue_id != f"mentor_queue_{expected[:20]}":
        raise ValueError("M46 mentor-queue identity mismatch")
    if queue.participant_id != view.participant_id:
        raise ValueError("M46 mentor-queue participant mismatch")
    if item not in queue.items:
        raise ValueError("M46 mentor-queue item is not in the exact queue")
    context = session.capture_session.context
    if item.game_id != context.game_id or item.position_id != context.position_id:
        raise ValueError("M46 mentor-queue item does not match tutor position")
    if item.hypothesis_ids and hypothesis_id not in item.hypothesis_ids:
        raise ValueError("M46 mentor-queue item does not reference selected hypothesis")
    return _queue_ref(queue), _queue_item_ref(item)


def _validate_transfer_context(
    *,
    plan: TransferRetestPlan | None,
    view: LearnerProgressView,
    session: TutorSession,
    hypothesis: LearnerProgressHypothesis,
) -> EvidenceSynthesisReference | None:
    if plan is None:
        return None
    expected = _digest(plan.identity_payload())
    if plan.fingerprint != expected:
        raise ValueError("M46 M42 transfer-plan fingerprint mismatch")
    if plan.transfer_plan_id != f"transfer_retest_plan_{expected[:20]}":
        raise ValueError("M46 M42 transfer-plan identity mismatch")
    if plan.participant_id != view.participant_id:
        raise ValueError("M46 M42 participant mismatch")
    if plan.hypothesis_id != hypothesis.hypothesis_id:
        raise ValueError("M46 M42 hypothesis mismatch")
    if plan.hypothesis_revision_ref != hypothesis.current_revision_ref:
        raise ValueError("M46 M42 current-revision mismatch")
    if plan.next_session_plan_ref != view.next_session_plan_ref:
        raise ValueError("M46 M42/M44 next-session-plan mismatch")
    if plan.selected_candidate is None:
        raise ValueError("M46 requires a selected M42 position when a plan is supplied")
    context = session.capture_session.context
    selected = plan.selected_candidate.position
    if selected.game_id != context.game_id or selected.position_id != context.position_id:
        raise ValueError("M46 M42 selected position does not match tutor position")
    return _transfer_ref(plan)


def _recognition_question(hypothesis: LearnerProgressHypothesis) -> str | None:
    for concept in hypothesis.concepts:
        if concept.recognition_questions:
            return concept.recognition_questions[0]
    return None


def _choose_frozen_action(
    hypothesis: LearnerProgressHypothesis,
    *,
    transfer_plan: TransferRetestPlan | None,
    policy: AdaptiveTutorPolicy,
) -> tuple[
    AdaptiveTutorAction,
    str | None,
    ExposureEffect,
    ResponseEvidenceClass,
    tuple[str, ...],
    tuple[str, ...],
]:
    next_action = hypothesis.next_action
    if next_action in _TRANSFER_ACTIONS and transfer_plan is None:
        return (
            "NO_FURTHER_ACTION",
            None,
            "none",
            "none",
            ("M40 requests transfer testing but no exact M42 test plan is supplied.",),
            ("A qualified M42 transfer/retest plan is required before transfer tutoring.",),
        )
    if next_action == "WAIT_FOR_REAL_GAME_EVIDENCE":
        return (
            "NO_FURTHER_ACTION",
            None,
            "none",
            "none",
            ("M40 requests future real-game evidence rather than a tutor intervention.",),
            ("No current-session tutor action can manufacture real-game evidence.",),
        )
    if next_action in _EVIDENCE_ACTIONS and policy.evidence_actions_reveal_after_freeze:
        return (
            "REVEAL_ENGINE_LINE",
            None,
            "objective_reveal",
            "none",
            ("Clean M8 baseline evidence is frozen; objective reveal may now proceed.",),
            (),
        )
    recognition = _recognition_question(hypothesis)
    if (
        next_action == "TEACH_CONCEPT"
        and recognition is not None
        and policy.use_recognition_question_for_teaching
    ):
        return (
            "GIVE_CONCEPT_HINT",
            recognition,
            "assisted_followup",
            "assisted_followup",
            ("M40 proposes concept teaching and M44 supplies a recognition question.",),
            (),
        )
    if next_action in {"TEACH_CONCEPT", "ASSIGN_PRACTICE", *_TRANSFER_ACTIONS}:
        return (
            "GIVE_MINIMAL_HINT",
            "Re-examine the position using the target decision process before seeing the answer.",
            "assisted_followup",
            "assisted_followup",
            ("Baseline evidence is frozen; a bounded non-answer hint is now permitted.",),
            (),
        )
    return (
        "REVEAL_ENGINE_LINE",
        None,
        "objective_reveal",
        "none",
        ("Baseline evidence is frozen and no narrower bounded hint is warranted.",),
        (),
    )


def build_adaptive_tutor_proposal(
    *,
    tutor_session: TutorSession,
    learner_progress_view: LearnerProgressView,
    hypothesis_id: str,
    policy: AdaptiveTutorPolicy,
    created_at: str,
    mentor_queue: MentorQueue | None = None,
    mentor_queue_item: MentorQueueItem | None = None,
    transfer_plan: TransferRetestPlan | None = None,
) -> AdaptiveTutorProposal:
    """Choose one bounded next tutor action without executing it."""
    validate_adaptive_tutor_policy(policy)
    _validate_session(tutor_session)
    _validate_view(learner_progress_view)
    _timestamp("created_at", created_at)
    _nonempty("hypothesis_id", hypothesis_id)
    context = tutor_session.capture_session.context
    if context.participant_id != learner_progress_view.participant_id:
        raise ValueError("M46 M8/M44 participant mismatch")
    hypotheses = {
        item.hypothesis_id: item for item in learner_progress_view.hypotheses
    }
    hypothesis = hypotheses.get(hypothesis_id)
    if hypothesis is None:
        raise ValueError("M46 selected hypothesis is not in the M44 view")
    queue_ref, queue_item_ref = _validate_queue_context(
        queue=mentor_queue,
        item=mentor_queue_item,
        view=learner_progress_view,
        session=tutor_session,
        hypothesis_id=hypothesis_id,
    )
    transfer_ref = _validate_transfer_context(
        plan=transfer_plan,
        view=learner_progress_view,
        session=tutor_session,
        hypothesis=hypothesis,
    )

    state = tutor_session.state
    if state in _PRE_BASELINE_STATES:
        action: AdaptiveTutorAction = "CONTINUE_BASELINE_CAPTURE"
        prompt = None
        exposure: ExposureEffect = "none"
        response_class: ResponseEvidenceClass = "baseline_unassisted"
        reasons = (
            "M8 pre-reveal baseline is not fully frozen; adaptive tutoring is blocked.",
        )
        blocking = (
            "Complete the existing qualified M8 capture protocol before hints or reveals.",
        )
    elif state == "frozen":
        (
            action,
            prompt,
            exposure,
            response_class,
            reasons,
            blocking,
        ) = _choose_frozen_action(
            hypothesis,
            transfer_plan=transfer_plan,
            policy=policy,
        )
    elif state in _POST_REVEAL_STATES and policy.post_reveal_reflection:
        action = "ASK_REFLECTION"
        prompt = (
            "What changed between your initial reasoning and the objective evidence, "
            "and what cue would you look for next time?"
        )
        exposure = "post_reveal"
        response_class = "post_reveal_reflection"
        reasons = (
            "Objective evidence is already revealed; any new response is post-reveal reflection.",
        )
        blocking = ()
    elif state == "completed":
        action = "NO_FURTHER_ACTION"
        prompt = None
        exposure = "none"
        response_class = "none"
        reasons = ("The exact M8 tutor session is already completed.",)
        blocking = ("Start a new qualified tutor session for additional interaction.",)
    else:
        raise ValueError(f"M46 does not support tutor session state {state!r}")

    concept_ids = tuple(concept.concept_id for concept in hypothesis.concepts)
    payload = {
        "schema_version": ADAPTIVE_TUTOR_PROPOSAL_SCHEMA_VERSION,
        "participant_id": learner_progress_view.participant_id,
        "tutor_session_ref": _session_ref(tutor_session).to_dict(),
        "learner_progress_view_ref": _view_ref(learner_progress_view).to_dict(),
        "mentor_queue_ref": None if queue_ref is None else queue_ref.to_dict(),
        "mentor_queue_item_ref": (
            None if queue_item_ref is None else queue_item_ref.to_dict()
        ),
        "transfer_plan_ref": None if transfer_ref is None else transfer_ref.to_dict(),
        "hypothesis_id": hypothesis.hypothesis_id,
        "hypothesis_revision_ref": hypothesis.current_revision_ref.to_dict(),
        "tutor_session_state": state,
        "learner_next_action": hypothesis.next_action,
        "action": action,
        "rendered_prompt": prompt,
        "concept_ids": list(concept_ids),
        "exposure_effect": exposure,
        "response_evidence_class": response_class,
        "reasons": list(reasons),
        "blocking_uncertainty": list(blocking),
        "policy_ref": policy.ref.to_dict(),
        "created_at": created_at,
        "execution_authority": "proposal_only",
        "model_language": "not_generated",
        "mastery": "not_established",
    }
    fingerprint = _digest(payload)
    return AdaptiveTutorProposal(
        proposal_id=f"adaptive_tutor_proposal_{fingerprint[:20]}",
        fingerprint=fingerprint,
        participant_id=learner_progress_view.participant_id,
        tutor_session_ref=_session_ref(tutor_session),
        learner_progress_view_ref=_view_ref(learner_progress_view),
        mentor_queue_ref=queue_ref,
        mentor_queue_item_ref=queue_item_ref,
        transfer_plan_ref=transfer_ref,
        hypothesis_id=hypothesis.hypothesis_id,
        hypothesis_revision_ref=hypothesis.current_revision_ref,
        tutor_session_state=state,
        learner_next_action=hypothesis.next_action,
        action=action,
        rendered_prompt=prompt,
        concept_ids=concept_ids,
        exposure_effect=exposure,
        response_evidence_class=response_class,
        reasons=reasons,
        blocking_uncertainty=blocking,
        policy_ref=policy.ref,
        created_at=created_at,
    )


def validate_adaptive_tutor_proposal(
    proposal: AdaptiveTutorProposal,
    *,
    tutor_session: TutorSession,
    learner_progress_view: LearnerProgressView,
    hypothesis_id: str,
    policy: AdaptiveTutorPolicy,
    mentor_queue: MentorQueue | None = None,
    mentor_queue_item: MentorQueueItem | None = None,
    transfer_plan: TransferRetestPlan | None = None,
) -> None:
    expected = build_adaptive_tutor_proposal(
        tutor_session=tutor_session,
        learner_progress_view=learner_progress_view,
        hypothesis_id=hypothesis_id,
        policy=policy,
        created_at=proposal.created_at,
        mentor_queue=mentor_queue,
        mentor_queue_item=mentor_queue_item,
        transfer_plan=transfer_plan,
    )
    if expected != proposal:
        raise ValueError("M46 adaptive-tutor proposal mismatch")
