"""Chess Knowledge Ontology public surface."""

from .assertions import (
    KNOWLEDGE_ASSERTION_BUNDLE_SCHEMA_VERSION,
    KNOWLEDGE_ASSERTION_SCHEMA_VERSION,
    KnowledgeAssertion,
    KnowledgeAssertionBundle,
    KnowledgeAssertionRef,
    KnowledgeEvidenceRef,
    KnowledgeProvenance,
    KnowledgeQualifier,
    KnowledgeSubject,
    build_assertion_bundle,
    build_knowledge_assertion,
    validate_assertion_bundle,
    validate_knowledge_assertion,
)
from .fingerprints import concept_fingerprint, ontology_fingerprint
from .learner_projection import (
    HYPOTHESIS_KNOWLEDGE_PROJECTION_SCHEMA_VERSION,
    HypothesisKnowledgeConceptSummary,
    HypothesisKnowledgeOccurrence,
    HypothesisKnowledgeProjection,
    HypothesisKnowledgeUnitProjection,
    build_hypothesis_knowledge_projection,
    validate_hypothesis_knowledge_projection,
)
from .model import (
    AuthorityClass,
    ChessConcept,
    ConceptKind,
    ConceptRelationship,
    DetectionSupport,
    ExternalMapping,
    OntologyDocument,
    PedagogyMetadata,
)
from .projection import (
    KNOWLEDGE_COACHING_CONTEXT_SCHEMA_VERSION,
    KNOWLEDGE_MODEL_BINDING_SCHEMA_VERSION,
    KNOWLEDGE_MODEL_INSTRUCTIONS,
    KnowledgeCoachingContext,
    KnowledgeContextAssertion,
    KnowledgeModelBinding,
    bind_knowledge_context_to_model_request,
    build_knowledge_augmented_provider_payload,
    build_knowledge_coaching_context,
    validate_knowledge_coaching_context,
    validate_knowledge_model_binding,
)
from .registry import (
    DEFAULT_ONTOLOGY_RESOURCE,
    DEFAULT_ONTOLOGY_RESOURCES,
    ONTOLOGY_SCHEMA_VERSION,
    OntologyLoadError,
    OntologyRegistry,
)
from .validation import OntologyValidationError, validate_ontology

__all__ = [
    "AuthorityClass",
    "ChessConcept",
    "ConceptKind",
    "ConceptRelationship",
    "DEFAULT_ONTOLOGY_RESOURCE",
    "DEFAULT_ONTOLOGY_RESOURCES",
    "DetectionSupport",
    "ExternalMapping",
    "HYPOTHESIS_KNOWLEDGE_PROJECTION_SCHEMA_VERSION",
    "HypothesisKnowledgeConceptSummary",
    "HypothesisKnowledgeOccurrence",
    "HypothesisKnowledgeProjection",
    "HypothesisKnowledgeUnitProjection",
    "KNOWLEDGE_ASSERTION_BUNDLE_SCHEMA_VERSION",
    "KNOWLEDGE_ASSERTION_SCHEMA_VERSION",
    "KNOWLEDGE_COACHING_CONTEXT_SCHEMA_VERSION",
    "KNOWLEDGE_MODEL_BINDING_SCHEMA_VERSION",
    "KNOWLEDGE_MODEL_INSTRUCTIONS",
    "KnowledgeAssertion",
    "KnowledgeAssertionBundle",
    "KnowledgeAssertionRef",
    "KnowledgeCoachingContext",
    "KnowledgeContextAssertion",
    "KnowledgeEvidenceRef",
    "KnowledgeModelBinding",
    "KnowledgeProvenance",
    "KnowledgeQualifier",
    "KnowledgeSubject",
    "ONTOLOGY_SCHEMA_VERSION",
    "OntologyDocument",
    "OntologyLoadError",
    "OntologyRegistry",
    "OntologyValidationError",
    "PedagogyMetadata",
    "bind_knowledge_context_to_model_request",
    "build_assertion_bundle",
    "build_hypothesis_knowledge_projection",
    "build_knowledge_augmented_provider_payload",
    "build_knowledge_assertion",
    "build_knowledge_coaching_context",
    "concept_fingerprint",
    "ontology_fingerprint",
    "validate_assertion_bundle",
    "validate_hypothesis_knowledge_projection",
    "validate_knowledge_assertion",
    "validate_knowledge_coaching_context",
    "validate_knowledge_model_binding",
    "validate_ontology",
]
