"""Deterministic learner-intelligence projections over qualified evidence."""

from .evidence_acquisition import (
    EVIDENCE_ACQUISITION_PLAN_SCHEMA_VERSION,
    EVIDENCE_ACQUISITION_POLICY_SCHEMA_VERSION,
    EvidenceAcquisitionCandidate,
    EvidenceAcquisitionIntent,
    EvidenceAcquisitionPlan,
    EvidenceAcquisitionPolicy,
    EvidenceAcquisitionPolicyRef,
    EvidenceCandidateKind,
    EvidenceCandidateOrigin,
    SemanticCoverage,
    build_default_evidence_acquisition_policy,
    build_evidence_acquisition_plan,
    validate_evidence_acquisition_plan,
    validate_evidence_acquisition_policy,
)
from .evidence_synthesis import (
    HYPOTHESIS_EVIDENCE_SYNTHESIS_SCHEMA_VERSION,
    EvidenceSynthesisReference,
    HypothesisEvidenceCounts,
    HypothesisEvidenceSynthesis,
    HypothesisEvidenceUnitSynthesis,
    HypothesisReviewSummary,
    build_hypothesis_evidence_synthesis,
    validate_hypothesis_evidence_synthesis,
)
from .next_session import (
    NEXT_SESSION_PLAN_SCHEMA_VERSION,
    NEXT_SESSION_POLICY_SCHEMA_VERSION,
    NextSessionAction,
    NextSessionActionCandidate,
    NextSessionPlan,
    NextSessionPolicy,
    NextSessionPolicyRef,
    build_default_next_session_policy,
    build_next_session_plan,
    validate_next_session_plan,
    validate_next_session_policy,
)

__all__ = [
    "EVIDENCE_ACQUISITION_PLAN_SCHEMA_VERSION",
    "EVIDENCE_ACQUISITION_POLICY_SCHEMA_VERSION",
    "HYPOTHESIS_EVIDENCE_SYNTHESIS_SCHEMA_VERSION",
    "NEXT_SESSION_PLAN_SCHEMA_VERSION",
    "NEXT_SESSION_POLICY_SCHEMA_VERSION",
    "EvidenceAcquisitionCandidate",
    "EvidenceAcquisitionIntent",
    "EvidenceAcquisitionPlan",
    "EvidenceAcquisitionPolicy",
    "EvidenceAcquisitionPolicyRef",
    "EvidenceCandidateKind",
    "EvidenceCandidateOrigin",
    "EvidenceSynthesisReference",
    "HypothesisEvidenceCounts",
    "HypothesisEvidenceSynthesis",
    "HypothesisEvidenceUnitSynthesis",
    "HypothesisReviewSummary",
    "NextSessionAction",
    "NextSessionActionCandidate",
    "NextSessionPlan",
    "NextSessionPolicy",
    "NextSessionPolicyRef",
    "SemanticCoverage",
    "build_default_evidence_acquisition_policy",
    "build_default_next_session_policy",
    "build_evidence_acquisition_plan",
    "build_hypothesis_evidence_synthesis",
    "build_next_session_plan",
    "validate_evidence_acquisition_plan",
    "validate_evidence_acquisition_policy",
    "validate_hypothesis_evidence_synthesis",
    "validate_next_session_plan",
    "validate_next_session_policy",
]
